import type {
  ActionItem,
  ActivityEvent,
  DashboardNotification,
  InventoryAlert,
  MerchantSession,
  Metric,
  PipelineStage,
  ProductRow,
  RecentOrder,
} from "@/features/merchant-dashboard/dashboard-types";
import { rolePermissions } from "@/features/merchant-dashboard/dashboard-access";

export const documentationMerchantSession: MerchantSession = {
  defaultLocation: "Lumière Makati Warehouse",
  displayName: "Althea",
  email: "owner@example.com",
  merchantHandle: "documentation-only",
  merchantName: "Lumière",
  permissions: rolePermissions["Merchant Owner"],
  role: "Merchant Owner",
  storeStatus: "active",
  verified: true,
};

const productImages = {
  blouse: require("@/assets/images/storefront/dahlia-ruffle-top.jpg"),
  cardigan: require("@/assets/images/storefront/lena-flower-knit.jpg"),
  dress: require("@/assets/images/storefront/rosebud-midi-dress.jpg"),
  skirt: require("@/assets/images/storefront/amour-slip-skirt.jpg"),
  tote: require("@/assets/images/storefront/petal-shoulder-bag.jpg"),
} as const;

export const dashboardMetrics: Metric[] = [
  {
    changePercent: 12.4,
    comparison: "₱432,640 vs previous 7 days",
    key: "gross-sales",
    label: "Gross sales",
    sparkline: [42, 48, 39, 55, 51, 67, 72],
    value: "₱486,275",
    valueCentavos: 48627500,
  },
  {
    changePercent: 8.1,
    comparison: "294 vs previous 7 days",
    key: "orders",
    label: "Orders",
    sparkline: [34, 38, 31, 43, 40, 52, 62],
    value: "318",
  },
  {
    changePercent: 9.6,
    comparison: "₱377,120 vs previous 7 days",
    key: "net-earnings",
    label: "Net earnings",
    sparkline: [35, 46, 40, 59, 54, 68, 74],
    value: "₱413,334",
    valueCentavos: 41333400,
  },
  {
    changePercent: -2.3,
    comparison: "₱1,565 vs previous 7 days",
    key: "average-order-value",
    label: "Average order value",
    sparkline: [68, 56, 74, 52, 45, 40, 32],
    value: "₱1,529",
    valueCentavos: 152900,
  },
];

export const chartSeries = [
  { label: "Jul 25", orders: 32, refunds: 1800, revenue: 58100 },
  { label: "Jul 26", orders: 41, refunds: 900, revenue: 67400 },
  { label: "Jul 27", orders: 29, refunds: 1220, revenue: 51700 },
  { label: "Jul 28", orders: 45, refunds: 1040, revenue: 74200 },
  { label: "Jul 29", orders: 42, refunds: 1670, revenue: 68400 },
  { label: "Jul 30", orders: 51, refunds: 1930, revenue: 80500 },
  { label: "Jul 31", orders: 53, refunds: 1920, revenue: 83975 },
];

export const pipelineStages: PipelineStage[] = [
  { count: 18, key: "new", label: "New", tone: "pink" },
  { count: 24, key: "confirmed", label: "Confirmed", tone: "blue" },
  { count: 31, key: "processing", label: "Processing", tone: "blue" },
  { count: 12, key: "ready", label: "Ready to ship", tone: "warning" },
  { count: 46, key: "shipped", label: "Shipped", tone: "blue" },
  { count: 182, key: "delivered", label: "Delivered", tone: "green" },
  { count: 5, key: "cancelled", label: "Cancelled", tone: "neutral" },
];

export const actionItems: ActionItem[] = [
  {
    action: "Complete details",
    count: 7,
    key: "missing-details",
    label: "Products missing required information",
    permission: "products.write",
    severity: "critical",
  },
  {
    action: "Restock",
    count: 3,
    key: "out-of-stock",
    label: "Out-of-stock variants",
    permission: "inventory.adjust",
    severity: "critical",
  },
  {
    action: "Fulfill orders",
    count: 9,
    key: "awaiting-fulfillment",
    label: "Orders waiting for fulfillment",
    permission: "orders.fulfill",
    severity: "critical",
  },
  {
    action: "Review & publish",
    count: 4,
    key: "awaiting-publication",
    label: "Products awaiting publication",
    permission: "products.publish",
    severity: "warning",
  },
  {
    action: "Restock",
    count: 12,
    key: "low-stock",
    label: "Low-stock variants",
    permission: "inventory.adjust",
    severity: "warning",
  },
  {
    action: "Update profile",
    count: 1,
    key: "profile-issues",
    label: "Merchant profile issues",
    permission: "merchant.profile.update",
    severity: "review",
  },
];

export const topProducts: ProductRow[] = [
  {
    image: productImages.dress,
    name: "Amihan Linen Wrap Dress",
    revenueCentavos: 8947200,
    sku: "LUM-DRS-016",
    stockStatus: "In stock",
    trendPercent: 18.4,
    units: 128,
  },
  {
    image: productImages.blouse,
    name: "Sampaguita Silk Blouse",
    revenueCentavos: 5568000,
    sku: "LUM-TOP-071",
    stockStatus: "Low stock",
    trendPercent: 9.2,
    units: 96,
  },
  {
    image: productImages.tote,
    name: "Habi Weave Tote",
    revenueCentavos: 4218000,
    sku: "LUM-BAG-032",
    stockStatus: "In stock",
    trendPercent: 4.6,
    units: 74,
  },
  {
    image: productImages.cardigan,
    name: "Baybayin Knit Cardigan",
    revenueCentavos: 3843000,
    sku: "LUM-KNT-008",
    stockStatus: "Out of stock",
    trendPercent: -6.1,
    units: 61,
  },
  {
    image: productImages.skirt,
    name: "Tala Slip Skirt",
    revenueCentavos: 2704000,
    sku: "LUM-SKT-045",
    stockStatus: "In stock",
    trendPercent: 2.1,
    units: 52,
  },
];

export const recentOrders: RecentOrder[] = [
  {
    customer: "Maria Santos",
    date: "Aug 1, 2026",
    fulfillment: "Unfulfilled",
    items: 3,
    orderNumber: "LUM-24817",
    payment: "Paid",
    status: "New",
    totalCentavos: 489900,
  },
  {
    customer: "Jonas Reyes",
    date: "Aug 1, 2026",
    fulfillment: "Packing",
    items: 1,
    orderNumber: "LUM-24816",
    payment: "Paid",
    status: "Processing",
    totalCentavos: 199900,
  },
  {
    customer: "Camille Bautista",
    date: "Aug 1, 2026",
    fulfillment: "Unfulfilled",
    items: 5,
    orderNumber: "LUM-24815",
    payment: "Pending",
    status: "New",
    totalCentavos: 872500,
  },
  {
    customer: "Rafael Dizon",
    date: "Jul 31, 2026",
    fulfillment: "Shipped",
    items: 2,
    orderNumber: "LUM-24814",
    payment: "Paid",
    status: "Shipped",
    totalCentavos: 268000,
  },
  {
    customer: "Liza Mercado",
    date: "Jul 31, 2026",
    fulfillment: "Delivered",
    items: 4,
    orderNumber: "LUM-24813",
    payment: "Paid",
    status: "Delivered",
    totalCentavos: 634000,
  },
  {
    customer: "Andrei Villanueva",
    date: "Jul 31, 2026",
    fulfillment: "Delivered",
    items: 1,
    orderNumber: "LUM-24812",
    payment: "Refunded",
    status: "Cancelled",
    totalCentavos: 98000,
  },
  {
    customer: "Bea Navarro",
    date: "Jul 30, 2026",
    fulfillment: "Packing",
    items: 2,
    orderNumber: "LUM-24811",
    payment: "Paid",
    status: "Processing",
    totalCentavos: 356000,
  },
  {
    customer: "Paolo Cruz",
    date: "Jul 30, 2026",
    fulfillment: "Delivered",
    items: 3,
    orderNumber: "LUM-24810",
    payment: "Paid",
    status: "Delivered",
    totalCentavos: 525000,
  },
  {
    customer: "Nina Flores",
    date: "Jul 29, 2026",
    fulfillment: "Shipped",
    items: 1,
    orderNumber: "LUM-24809",
    payment: "Paid",
    status: "Shipped",
    totalCentavos: 189000,
  },
  {
    customer: "Miguel Ramos",
    date: "Jul 29, 2026",
    fulfillment: "Delivered",
    items: 2,
    orderNumber: "LUM-24808",
    payment: "Paid",
    status: "Delivered",
    totalCentavos: 418000,
  },
  {
    customer: "Aya Mendoza",
    date: "Jul 28, 2026",
    fulfillment: "Unfulfilled",
    items: 4,
    orderNumber: "LUM-24807",
    payment: "Pending",
    status: "New",
    totalCentavos: 742000,
  },
  {
    customer: "Carlo Garcia",
    date: "Jul 28, 2026",
    fulfillment: "Delivered",
    items: 2,
    orderNumber: "LUM-24806",
    payment: "Paid",
    status: "Delivered",
    totalCentavos: 322000,
  },
  {
    customer: "Trina Lim",
    date: "Jul 27, 2026",
    fulfillment: "Packing",
    items: 3,
    orderNumber: "LUM-24805",
    payment: "Paid",
    status: "Processing",
    totalCentavos: 577000,
  },
  {
    customer: "Luis Aquino",
    date: "Jul 27, 2026",
    fulfillment: "Delivered",
    items: 1,
    orderNumber: "LUM-24804",
    payment: "Paid",
    status: "Delivered",
    totalCentavos: 149000,
  },
];

export const lowStockAlerts: InventoryAlert[] = [
  {
    available: 4,
    image: productImages.blouse,
    location: "Lumière Makati Warehouse",
    name: "Sampaguita Silk Blouse",
    onHand: 9,
    reorderThreshold: 10,
    reserved: 5,
    sku: "LUM-TOP-071-IV-S",
    variant: "Ivory / S",
  },
  {
    available: 0,
    image: productImages.cardigan,
    location: "Lumière Makati Warehouse",
    name: "Baybayin Knit Cardigan",
    onHand: 2,
    reorderThreshold: 8,
    reserved: 2,
    sku: "LUM-KNT-008-CL-M",
    variant: "Clay / M",
  },
  {
    available: 4,
    image: productImages.dress,
    location: "Lumière Cebu Studio",
    name: "Amihan Linen Wrap Dress",
    onHand: 7,
    reorderThreshold: 12,
    reserved: 3,
    sku: "LUM-DRS-016-SA-L",
    variant: "Sand / L",
  },
  {
    available: 1,
    image: productImages.tote,
    location: "Lumière Makati Warehouse",
    name: "Habi Weave Tote",
    onHand: 6,
    reorderThreshold: 10,
    reserved: 5,
    sku: "LUM-BAG-032-IN-OS",
    variant: "Indigo / One size",
  },
];

export const activityEvents: ActivityEvent[] = [
  {
    actor: "Joyce (Fulfillment Staff)",
    key: "order-shipped",
    summary: "Order LUM-24814 was marked as shipped",
    time: "4 minutes ago",
    tone: "green",
    type: "order",
  },
  {
    actor: "Marco (Inventory Staff)",
    key: "stock-adjusted",
    summary: "Stock adjusted for Sampaguita Silk Blouse (Ivory / S)",
    time: "48 minutes ago",
    tone: "blue",
    type: "inventory",
  },
  {
    actor: "Althea (Merchant Owner)",
    key: "product-published",
    summary: "Tala Slip Skirt was published to the storefront",
    time: "2 hours ago",
    tone: "pink",
    type: "product",
  },
  {
    actor: "Kim (Catalog Staff)",
    key: "images-added",
    summary: "3 images added to Amihan Linen Wrap Dress",
    time: "4 hours ago",
    tone: "blue",
    type: "image",
  },
  {
    actor: "Althea (Merchant Owner)",
    key: "staff-access",
    summary: "Support Staff access granted to a team member",
    time: "Yesterday",
    tone: "warning",
    type: "staff",
  },
  {
    actor: "Althea (Merchant Owner)",
    key: "profile-updated",
    summary: "Merchant profile return policy updated",
    time: "Yesterday",
    tone: "neutral",
    type: "profile",
  },
];

export const dashboardNotifications: DashboardNotification[] = [
  {
    key: "fulfillment",
    message: "9 orders are waiting for fulfillment",
    time: "10 minutes ago",
    unread: true,
  },
  {
    key: "out-of-stock",
    message: "Baybayin Knit Cardigan is out of stock",
    time: "1 hour ago",
    unread: true,
  },
  {
    key: "payout",
    message: "Payout for July has been scheduled",
    time: "3 hours ago",
    unread: true,
  },
  {
    key: "publication",
    message: "4 products are awaiting publication",
    time: "Yesterday",
    unread: false,
  },
];
